% Get some values for all regions (from the saved R image)
\newcommand{\regionName}{\Sexpr{unique(areas$RegionName)}}
\newcommand{\regionType}{\Sexpr{regionType}}
\newcommand{\firstYr}{\Sexpr{min(yrRange)}}
\newcommand{\thisYr}{\Sexpr{max(yrRange)}}
\newcommand{\fishName}{Pacific Herring}
\newcommand{\scienceName}{\emph{Clupea pallasii}}

% Get some values for CC region (from the saved R image)
\newcommand{\histYrs}{\Sexpr{histYrs}}
\newcommand{\histRat}{\Sexpr{histRat}}
\newcommand{\fixYrs}{\Sexpr{fixYrs}}

% Note if there is only a subset of sections
\newcommand{\isSubset}{\Sexpr{ifelse(all(is.na(sectionSub)), "", paste("Note that this report contains data collected in a subset of the SAR; included sections are ", PasteNicely(sectionSub), ".", sep=""))}}

% Initialize switches; set to TRUE/FALSE in R based on conditions in the region
\newtoggle{biosamples}  % Show biosample locations
\Sexpr{tfBiosamples}
\newtoggle{weightCatch}  % Show weight by catch type
\Sexpr{tfWeightCatch}
\newtoggle{weightGroup}  % Show weight by group
\Sexpr{tfWeightGroup}
\newtoggle{spawnDepth}  % Show depth of spawn
\Sexpr{tfSpawnDepth}
\newtoggle{numPropWtAge}  % Show number-, proportion- and weight-at-age
\Sexpr{tfNumPropWtAge}
\newtoggle{catchStatArea}  % Show catch by stat area
\Sexpr{tfCatchStatArea}
\newtoggle{spawnByLoc}  % Show spawn locations
\Sexpr{tfSpawnByLoc}
\newtoggle{spawnByLocXY}  % Show spawn locations with X and Y
\Sexpr{tfSpawnByLocXY}
\newtoggle{spatialGroup}  % Show table of stat areas, sections, and groups
\Sexpr{tfSpatialGroup}

% Location of the pdf figures (generated in R)
\graphicspath{{\Sexpr{noquote(rPath)}}}

% Some common notes and comments
\newcommand{\sampleSize}{Each sample is approximately 100 fish.}
\newcommand{\seineSamples}{Biological summaries only include samples collected using seine nets (commercial and test) due to size-selectivity of other gear types such as gillnet.}
\newcommand{\repSamples}{Only representative biological samples are included, where `representative' indicates whether the \fishName{} sample in the set accurately reflects the larger \fishName{} school.}
\newcommand{\plusGroup}{The age-\Sexpr{max(ageRange)} class is a `plus group' which includes fish ages \Sexpr{max(ageRange)} and older.}
\newcommand{\spawnIndex}{The `spawn index' is not scaled by the spawn survey scaling parameter, $q$.}
\newcommand{\trendLine}{The thick black line is a \Sexpr{smLine} curve, and the shaded area is the \Sexpr{ciLevel*100}\% confidence interval.}
\newcommand{\qPeriods}{The spawn index has two distinct periods defined by the dominant survey method: surface surveys (\Sexpr{qYrs$q1}), and dive surveys (\Sexpr{qYrs$q2}).}
\newcommand{\legendNear}{Legend: `Nearshore' refers to samples collected using cast nets as part of a pilot study with First Nations.}
\newcommand{\legendGear}{Legend: `Other' represents the reduction, the food and bait, as well as the special use fishery; `RoeSN' represents the roe seine fishery; and `RoeGN' represents the roe gillnet fishery.}
\newcommand{\darkThisYr}{The year \thisYr{} has a darker bar to facilitate interpretation.}
\newcommand{\withPrivacy}[1]{Note: data may be withheld due to privacy concerns (#1).}
\newcommand{\noSOK}{Data from the spawn-on-kelp (SOK) fishery are not included.}
\newcommand{\spawnIndexTechReport}{See the \href{https://github.com/grinnellm/SpawnIndex/blob/master/tr/Draft.pdf}{draft spawn index technical report} for calculations to convert SOK harvest to spawning biomass.}
\newcommand{\missingSpawn}[1]{Missing spawn index values (#1) indicate incomplete spawn surveys.}
\newcommand{\spawnTypes}{There are three types of spawn survey observations: observations of spawn taken from the surface usually at low tide, underwater observations of spawn on giant kelp, Macrocystis (\emph{Macrocystis} spp.), and underwater observations of spawn on other types of algae and the substrate, which we refer to as `understory.'}
\newcommand{\pctChange}[1]{Percent change is $\delta_t=\frac{\alpha_t - \alpha_{t-1}}{\alpha_{t-1}}$ where $\alpha_t$ is the #1 in year $t$.}
\newcommand{\covid}{\section{COVID-19 pandemic}
The COVID-19 pandemic impacted our ability to collect and analyse Pacific Herring data throughout British Columbia in 2020.
The pandemic and associated provincial response changed rapidly during the Pacific Herring field program season.
Despite these challenges, surveyors assessed all major observed spawns in the \Sexpr{length(allRegions$major)} major stock assessment regions (SARs).
However, these changes impacted our ability to assess spawn in SARs with later spawns more than SARs with earlier spawns.
For example, spawns were surveyed by surface surveys instead of underwater dive surveys in Prince Rupert District and Haida Gwaii.\par
Although Pacific Herring biological samples were collected as usual, the pandemic delayed the analysis of biological data for all SARs.
This delay is most notable for age data which are analysed at the sclerochronology lab at the Pacific Biological Station.
This lab closed on March \nth{16}, and resumed limited ageing analysis on July \nth{6}.
This has resulted in delayed provision of age data for Pacific Herring and many other species.
To address this backlog efficiently, senior science staff and fisheries managers at DFO are prioritizing species to analyse in the sclerochronology lab.
Unfortunately, it may not be possible to analyse all the Pacific Herring age data in time for stock assessments this year.
Note that although age data are not required for Pacific Herring stock assessments, they are an important component.\par
Due to the delay in the analysis of biological data, some tables and figures showing biological data have been omitted from this version of the report.
Other tables and figures are included, but they do not have biological data for 2020.
We will update data summary reports with 2020 biological data when available.
We appreciate your patience and understanding as we continue to work from home in these uncertain and changing times.}
