% Get some values for all regions (from the saved R image)
\newcommand{\regionName}{\Sexpr{unique(areas$RegionName)}}
\newcommand{\regionType}{\Sexpr{regionType}}
\newcommand{\firstYr}{\Sexpr{min(yrRange)}}
\newcommand{\thisYr}{\Sexpr{max(yrRange)}}
\newcommand{\fishName}{Pacific Herring}
\newcommand{\scienceName}{\emph{Clupea pallasii}}

% Get some values for CC region (from the saved R image)
\newcommand{\histYrs}{\Sexpr{histYrs}}
\newcommand{\histRat}{\Sexpr{histRat}}
\newcommand{\fixYrs}{\Sexpr{fixYrs}}
\newcommand{\sectionsJS}{\Sexpr{sectionsJS}}

% Note if there is only a subset of sections
\newcommand{\isSubset}{\Sexpr{ifelse(all(is.na(sectionSub)), "", paste("Note that this report contains data collected in a subset of the SAR; included sections are ", PasteNicely(sectionSub), ".", sep=""))}}

% Initialize switches; set to TRUE/FALSE in R based on conditions in the region
\newtoggle{major}  % Is it a major SAR?
\Sexpr{tfMajor}
\newtoggle{biosamples}  % Show biosample locations
\Sexpr{tfBiosamples}
\newtoggle{weightCatch}  % Show weight by catch type
\Sexpr{tfWeightCatch}
\newtoggle{weightGroup}  % Show weight by group
\Sexpr{tfWeightGroup}
\newtoggle{spawnDepth}  % Show depth of spawn
\Sexpr{tfSpawnDepth}
\newtoggle{numPropWtAge}  % Show number-, proportion- and weight-at-age
\Sexpr{tfNumPropWtAge}
\newtoggle{catchStatArea}  % Show catch by stat area
\Sexpr{tfCatchStatArea}
\newtoggle{spawnByLoc}  % Show spawn locations
\Sexpr{tfSpawnByLoc}
\newtoggle{spawnByLocXY}  % Show spawn locations with X and Y
\Sexpr{tfSpawnByLocXY}
\newtoggle{spatialGroup}  % Show table of stat areas, sections, and groups
\Sexpr{tfSpatialGroup}
\newtoggle{specialRegion} % Is this a special region
\Sexpr{tfSpecialRegion}
\newtoggle{showCatchZoom} % Show zoom area for catch
\Sexpr{tfShowCatchZoom}

% Location of the pdf figures (generated in R)
\graphicspath{{\Sexpr{noquote(rPath)}}}

% Some common notes and comments
\newcommand{\sampleSize}{Each sample is approximately 100 fish.}
\newcommand{\seineSamples}{Biological summaries only include samples collected using seine nets (commercial and test) due to size-selectivity of other gear types such as gillnet.}
\newcommand{\repSamples}{Only representative biological samples are included, where `representative' indicates whether the \fishName{} sample in the set accurately reflects the larger \fishName{} school.}
\newcommand{\plusGroup}{The age-\Sexpr{max(ageRange)} class is a `plus group' which includes fish ages \Sexpr{max(ageRange)} and older.}
\newcommand{\spawnIndex}{The `spawn index' is not scaled by the spawn survey scaling parameter, $q$.}
\newcommand{\trendLine}{The thick black line is a \Sexpr{smLine} curve, and the shaded area is the \Sexpr{ciLevel*100}\% confidence interval.}
\newcommand{\qPeriods}{The spawn index has two distinct periods defined by the dominant coastwide survey method: surface surveys (\Sexpr{qYrs$q1}), and dive surveys (\Sexpr{qYrs$q2}).}
\newcommand{\legendNear}{Legend: `Nearshore' refers to samples collected using cast nets as part of a pilot study with First Nations.}
\newcommand{\noteNear}{Note: Nearshore samples are not used in stock assessments.}
\newcommand{\legendGear}{Legend: `Other' represents the reduction (\Sexpr{min(yrRange)} to \Sexpr{lastRedYr} only), the food and bait, as well as the special use fishery; `RoeSN' represents the roe seine fishery; and `RoeGN' represents the roe gillnet fishery.}
\newcommand{\darkThisYr}{The year \thisYr{} has a darker bar to facilitate interpretation.}
\newcommand{\withPrivacy}[1]{Note: data may be withheld due to privacy concerns (#1).}
\newcommand{\noSOK}{Data from the spawn-on-kelp (SOK) fishery are not included.}
\newcommand{\spawnIndexTechReport}{See the \href{https://github.com/grinnellm/SpawnIndex/blob/master/tr/Draft.pdf}{draft spawn index technical report} for calculations to convert SOK harvest to spawning biomass.}
\newcommand{\missingSpawn}[1]{Missing spawn index values indicate incomplete surveys (#1).}
\newcommand{\spawnTypes}{There are three types of spawn survey observations: observations of spawn taken from the surface usually at low tide, underwater observations of spawn on giant kelp, Macrocystis (\emph{Macrocystis} spp.), and underwater observations of spawn on other types of algae and the substrate, which we refer to as `understory.'}
\newcommand{\pctChange}[1]{Percent change is $\delta_t=\frac{\alpha_t - \alpha_{t-1}}{\alpha_{t-1}}$ where $\alpha_t$ is the #1 in year $t$.}
\newcommand{\spawnSurfDive}{Note that spawn surveys in the dive survey period (\Sexpr{qYrs$q2}) are a combination of surface and dive surveys (Figures \ref{figSpawnIndexType} and \ref{figSpawnTypeProp}).}
\newcommand{\covid}{\section{COVID-19 pandemic}
Unlike the last three years,
the COVID-19 pandemic did not impact the collection and analysis of biological data in 2023, and
spawn surveys proceeded as usual.}
\newcommand{\specialRegion}{Note that special SARs are unofficial SARs; they are excluded in regular monitoring and analyses.}
