% Initialize switches; set to TRUE or FALSE in R based on the region
\newtoggle{biosamples}  % Show biosample locations
\Sexpr{tfBiosamples}
\newtoggle{weightCatch}  % Show weight by catch type
\Sexpr{tfWeightCatch}
\newtoggle{weightGroup}  % Show weight by group
\Sexpr{tfWeightGroup}
\newtoggle{spawnDepth}  % Show depth of spawn
\Sexpr{tfSpawnDepth}
\newtoggle{numPropWtAge}  % Show number-, proportion- and weight-at-age
\Sexpr{tfNumPropWtAge}

% Get some values for all regions (from the saved R image)
\newcommand{\regionName}{\Sexpr{unique(areas$RegionName)}}
\newcommand{\regionType}{region}
\newcommand{\firstYr}{\Sexpr{min(yrRange)}}
\newcommand{\thisYr}{\Sexpr{max(yrRange)}}

% Get some values for CC region (from the saved R image)
\newcommand{\histYrs}{\Sexpr{histYrs}}
\newcommand{\histRat}{\Sexpr{histRat}}
\newcommand{\fixYrs}{\Sexpr{fixYrs}}

% Location of the pdf figures (generated in R)
\graphicspath{{\Sexpr{noquote(rPath)}}}

% Some common notes and comments
\newcommand{\sampleSize}{Each sample is approximately 100 fish.}
\newcommand{\seineSamples}{Biological summaries only include samples collected using seine nets (commercial and test) due to size-selectivity of other gear types such as gillnet.}
\newcommand{\repSamples}{Only representative biological samples are included, where `representative' indicates whether the herring sample in the set accurately reflects the larger herring school.}
\newcommand{\plusGroup}{The age-\Sexpr{max(ageRange)} class is a `plus group' which includes fish ages \Sexpr{max(ageRange)} and older.}
\newcommand{\spawnIndex}{The `spawn index' represents the raw survey data only, and is not scaled by the spawn survey scaling parameter, $q$.}
\newcommand{\trendLine}{The thick black line is a \Sexpr{smLine} curve, and the shaded area is the \Sexpr{ciLevel*100}\% confidence interval.}
\newcommand{\qPeriods}{The spawn index has two distinct periods defined by the dominant survey method: surface surveys (\Sexpr{qYrs$q1}), and dive surveys (\Sexpr{qYrs$q2}).}
\newcommand{\legendNear}{Legend: `Nearshore' refers to samples collected using cast nets as part of a pilot study with WCVI First Nations.}
\newcommand{\legendPeriod}{Legend: `Gear1' represents the reduction, the food and bait, as well as the special use fishery; `Gear2' represents the roe seine fishery; and `Gear3' represents the roe gillnet fishery.}
\newcommand{\darkPolys}{Dark polygons indicate Sections 132 and 135, which are not officially included in the \regionName{} \regionType{}.}
\newcommand{\noteSects}{Sections 132 and 135 are not officially included in the \regionName{} \regionType{}.}
\newcommand{\SoG}{Note: `SoG' indicates the percentage from Sections 132 and 135, which are officially included in the Strait of Georgia (SoG) major stock area.}
